### ISSUE TITLE
Weird overlay and context menus, fault of new Plasma?

### ISSUE THREAD

**Issue by arshaharyoko** [yeyushengfan258/Harmony-kde#4]
Hi, this theme was working fine until i reinstalled my entire OS & KDE Plasma
**Before:**
![2021-07-31_17-35](https://user-images.githubusercontent.com/50770606/127737372-2b23d2f2-914b-46ab-8016-fd046e1dd6ad.png)

**After:**
![2021-07-31_17-34_2](https://user-images.githubusercontent.com/50770606/127737385-12796e58-649c-439e-be07-d875cd9c1bea.png)
![2021-07-31_17-33](https://user-images.githubusercontent.com/50770606/127737388-c97e141e-3686-40fa-b4e7-68f5cce0e990.png)
![2021-07-31_17-42](https://user-images.githubusercontent.com/50770606/127737391-fba4d138-99a9-4bcc-aeb3-80f096c9f16f.png)

Any possible fixes?

**Comment by yeyushengfan258** [comment]
Hello, you first try to see if my latest theme can be used normally, because I built it based on a set of templates.

**Comment by arshaharyoko** [comment]
> Hello, you first try to see if my latest theme can be used normally, because I built it based on a set of templates.

Ok i will use your latest theme instead.

**Comment by CTalvio** [comment]
This is caused by the "Shadowless menus and tooltips" option. Untick the option, and the theme will work without this issue.
